title: TripStore Blog page
description: TripStore Blog
author: TripStore Devlopers Team.
logo: /hcz-jekyll-blog/static/img/logo.png
github: https://github.com/codeasashu
about: Freelance developer

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
